#Pipeline name to show on the GitHub Actions Web UI
name: Checkstyle
on:
  pull_request:
    branches:
      - main
jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Change this to your project's Java version
          distribution: 'adopt'

      - name: Install Checkstyle
        run: |
          wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.5/checkstyle-10.5-all.jar -O checkstyle.jar
          echo 'checkstyle.jar downloaded.'

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c /google_checks.xml src/**/*.java
        # Adjust the path to your Checkstyle configuration file and source files

      - name: Upload Checkstyle Report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: checkstyle-result.xml  # Adjust if needed
